version: '3'

services:
  db:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
  server:
    build: ./server
    ports:
      - "3001:3001"
    depends_on:
      - db
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
